2024-10-22 22:35:06:ERROR>  Traceback (most recent call last):
  File "C:\AutoTrading2\windows\main_win\main_win.py", line 232, in loginBtnClicked
    raise ValueError
ValueError

